site_name: Nyarch Linux Wiki
repo_name: NyarchWiki
repo_url: https://github.com/NyarchLinux/NyarchWiki

nav:
    - 'index.md'
    - 'future_projects.md'
    - Installation:
         - 'installation.md'
         - 'nvidia.md'
         - 'install_nvidia_drivers.md'
         - 'nyarcher.md'
    - 'applications.md'
    - 'nyarchassistant.md'

theme:
  name: material
  logo: assets/nyarch-logo.png
  favicon: assets/nyarch-logo.png
  language: zh
  features:
    - navigation.instant.prefetch
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang:
        - en
        - zh
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          nav_translations:
            Installation: 安装
            Applications: 应用程序
            Future Projects: 未来项目
            Nyarch Assistant: Nyarch 助手
            Nyarcher: Nyarcher
            Nvidia Support: Nvidia 支持
            Install Nvidia Drivers: 安装 Nvidia 驱动

extra:
  homepage: "https://nyarchlinux.moe"
  alternate:
    - name: English
      link: /
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/NyarchLinux
      name: Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/NyarchLinux/NyarchLinux
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xuw6BNXXE7
      name: Discord
copyright: Copyright &copy; 2025 Nyarch Linux
